fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    staging: "git://github.com/nanliu/puppet-staging.git"
  symlinks:
    tomcat: "#{source_dir}"
